name: Check Commit

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:

  validate-formatting:
    name: Validate Formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Correct Swift Version
        uses: slashmo/install-swift@v0.1.0
        with:
          version: "5.8"
      - name: Build Formatting Tools
        run: |
          swift build --product swift-format
      - name: Validate swift formatting
        # We ignore unparseable files because, for some reason, Process.swift breaks swift-format
        run: |
          swift run swift-format \
            --in-place \
            --ignore-unparsable-files \
            --recursive Sources Tests
          git diff
          git diff-index --quiet HEAD --

  test:
    name: Test on Linux
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04, macos-13
            swift:
              version: "5.8"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Correct Swift Version
        uses: slashmo/install-swift@v0.1.0
        with:
          version: ${{ matrix.swift.version }}
      - run: swift build
      - run: swift test
      - run: swift run ScriptExample
