name: Check Commit

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  swift-branch: swift-5.8-release
  swift-tag: 5.8-RELEASE

jobs:

  validate-formatting:
    name: Validate Formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Correct Swift Version
        uses: compnerd/gha-setup-swift@main
        with:
          branch: ${{ env.swift-branch }}
          tag:  ${{ env.swift-tag }}
      - name: Build Formatting Tools
        run: |
          swift build --product swift-format
      - name: Validate swift formatting
        run: |
          swift run swift-format \
            --in-place \
            --recursive Sources Tests
          git diff
          git diff-index --quiet HEAD --

  test:
    name: Run Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Correct Swift Version
        uses: compnerd/gha-setup-swift@main
        with:
          branch: ${{ env.swift-branch }}
          tag:  ${{ env.swift-tag }}
      - run: swift build
      - run: swift test
      - run: swift run ScriptExample
